services:
  
  webhooks:
    container_name: webhooks
    build: .
    ports:
    - "3000:3000"
    volumes:
    - ./:/go/src/app
    networks:
    - developer

networks:
  developer:
    name: developer
